### ISSUE TITLE
Help connect and streamline collaboration between Make Teams and community contributors

### ISSUE THREAD

**Issue by gusaus** [WordPress/sustainability#14]
### Goals/action items
* Create standardized list of Team roles, skills, and commitments
* Provide clear/easy entry points for contributing to multiple Teams
* Provide clear/easy entry points for paid/sponsored contributions

### Related issues
* #15
* #13 - the issue and ensuing comments illustrate the challenges some new teams have (especially if they don't have mentors, experienced/sponsored contributors, funds, or other resources to help get up and running) 
* #4 - is related to #13 and could probably be consolidated
* #2 - contains a ChatGPT list of community contributor roles. If there's not yet a master list of community contributor roles residing somewhere on https://make.wordpress.org/, possibly this can be the start of another project we can contribute to!?! 

### Reference/resources
* [Make Team ecosystem work and how are we connected?](https://make.wordpress.org/summit/2023/08/24/community-summit-discussion-notes-how-does-the-make-team-ecosystem-work-and-how-are-we-connected/) (Community Summit discussion)
* [Communication and Collaboration – Finding Your Way Around WordPress](https://make.wordpress.org/summit/2023/09/03/community-summit-discussion-notes-communication-and-collaboration-finding-your-way-around-wordpress/) (Community Summit discussion)
* [Communicating on Make Team Blogs: discussions, proposals, announcements](https://make.wordpress.org/summit/2023/08/31/part-i-ii-communicating/) (Community Summit discussion)

**Comment by gusaus** [comment]
The initial list of ideas came from a combo of community summit discussions as well as some of the [admin tasks](https://github.com/WordPress/sustainability/issues?q=is%3Aissue+is%3Aopen+label%3Aadmin) that have been logged to address needs of a new team.

- [ ] #13 - the issue and ensuing comments illustrate the challenges some new teams have (especially if they don't have mentors, experienced/sponsored contributors, funds, or other resources to help get up and running) 
- [ ] #4 - is related to #13 and could probably be consolidated
- [ ] #2 - contains a ChatGPT list of community contributor roles. If there's not yet a master list of community contributor roles residing somewhere on https://make.wordpress.org/, possibly this can be the start of another project we can contribute to!?!

**Comment by gusaus** [comment]
In terms of solutions, we might want to not only look at aspects of this [Drupal community initiative](https://www.drupal.org/project/sustainability/issues/3325045) for inspiration but use the Open Website Alliance https://github.com/WordPress/sustainability/issues/19 as an opporunity to share ideas, pool resources, and collaborate.

Specifically the ideas for the [Drupal Contributor Guide](https://www.drupal.org/community/contributor-guide) most likely could apply to ways to improve and extend https://make.wordpress.org/ 

> - Update and restructure the [Contribution Areas landing page](https://www.drupal.org/community/contributor-guide/contribution-areas); consider consolidating with the [Community landing page](https://www.drupal.org/community)
> - Update and structure each contribution area so the landing pages are consistent and welcoming to contributors; standardize and include elements like team members (including an aggregate of contributor time), meetings, working groups, projects posts, sponsors, etc.
> - [Improve and extend contributor task, role, and skill pages](https://www.drupal.org/community/contributor-guide/reference-information/guidelines-contributor-guide/content-types)
