### ISSUE TITLE
Create and prioritize roadmap

### ISSUE THREAD

**Issue by gusaus** [WordPress/sustainability#3]
We need to create and prioritize our Roadmap. To do this we should work through the following steps:

- [ ] Populate our [Roadmap project](https://github.com/orgs/WordPress/projects/134) with ideas from the following:  
  - [ ] [Google doc](https://docs.google.com/document/d/1KVx33UCSSGl4Kra7myE7FkoN9Pg-VwAXqJR4-f3y3kk/edit?usp=sharing)
  - [x] [Roadmap Canvas](https://wordpress.slack.com/docs/T024MFP4J/F05NYEDM3AA)
  - [ ] Meeting Agendas/Discussions
  - [ ] #sustainability (WordPress Slack)
- [ ] #13
- [ ] Create additional steps as we proceed

**Comment by gusaus** [comment]
Closing this out as the [Roadmap project](https://github.com/orgs/WordPress/projects/134) exists and is fairly well organized.
